### ISSUE TITLE
v2.0.0 issue - no form appearing

### ISSUE THREAD

**Issue by ericfox83** [merchantprotocol/Magento-Paytrace-Payment-Gateway#2]
Hey Jonathon,

Thanks so much for uploading the newest version of this. I just downloaded the files and installed them to my server. I added all of my Paytrace credentials in the admin section, then went to test the module at checkout. The option is showing up, but when selected it's not generating the credit card form. Here's a screenshot (v3 is the new module you uploaded) - http://www.awesomescreenshot.com/image/835026/6373f3d8c8aabe9fa69587f4f0e7d116

I flushed my cache, logged out and back in, but can't seem to get it to work. Any thoughts on what I'm doing wrong?

I DO however have v1.0 still installed, because I still have it running on one of my websites. Once I have 2.0 working, i'm going to uninstall 1.0.

**Comment by Jonathonbyrd** [comment]
Eric, can you send over the credentials for your server so that I can 
get it working for you. I haven't tagged it as v2.0.0 because I was 
waiting for somebody to test it out.

-J




On 12/14/2015 08:12 AM, ericfox83 wrote:
> I flushed my cache, logged out and back in, but can't seem to get it 
> to work. Any thoughts on what I'm doing wrong?
.

**Comment by Jonathonbyrd** [comment]
My skype username is jonathonbyrd

-J

**Comment by Jonathonbyrd** [comment]
My Skype crashed as soon as I ssh into your server. I think there's a 
port conflict. So I'll just message you over TEXT on the number you gave 
me, or via email.

- Jonathon

**Comment by ericfox83** [comment]
Ok thanks

**Comment by ericfox83** [comment]
Everything seems to be working just fine now!
